steps:
  - label: ":eyes: Verify"
    command: verify.sh  
  - label: ":rocket: Deploy"
    command: deploy.sh
    env:
      ES_USER: "buildkite"
      KIBANA_URL: "http://kibana.nlsmith.com:5601"
      KIBANA_SPACE: alerts-as-code
    if: build.branch == "main" && build.pull_request.id != null

